# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:06:09+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class ChangesGetResponse(BaseModel):
    Changes: Optional[List[Dict[str, Any]]] = Field(
        None, description='The individual changes'
    )
    Done: Optional[bool] = Field(
        None,
        description='Whether the last reported change is the last of the full history',
    )
    Last: Optional[float] = Field(
        None,
        description='The index of the last reported change, can be used for the `since` argument in subsequent calls to this route',
    )


class InstancesPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='Orthanc identifier of the new instance'
    )
    ParentPatient: Optional[str] = Field(
        None, description='Orthanc identifier of the parent patient'
    )
    ParentSeries: Optional[str] = Field(
        None, description='Orthanc identifier of the parent series'
    )
    ParentStudy: Optional[str] = Field(
        None, description='Orthanc identifier of the parent study'
    )
    Path: Optional[str] = Field(
        None, description='Path to the new instance in the REST API'
    )
    Status: Optional[str] = Field(
        None,
        description='Can be `Success`, `AlreadyStored`, `Failure`, or `FilteredOut` (removed by some `NewInstanceFilter`)',
    )


class InstancesIdAnonymizePostRequest(BaseModel):
    DicomVersion: Optional[str] = Field(
        None,
        description='Version of the DICOM standard to be used for anonymization. Check out configuration option `DeidentifyLogsDicomVersion` for possible values.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='List of DICOM tags whose value must not be destroyed by the anonymization. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    KeepPrivateTags: Optional[bool] = Field(
        None,
        description='Keep the private tags from the DICOM instances (defaults to `false`)',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of additional tags to be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class InstancesIdModifyPostRequest(BaseModel):
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    RemovePrivateTags: Optional[bool] = Field(
        None,
        description='Remove the private tags from the DICOM instances (defaults to `false`)',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class IgnoreLength(RootModel[List[str]]):
    root: List[str]


class InstancesIdReconstructPostRequest(BaseModel):
    ReconstructFiles: Optional[bool] = Field(
        None,
        description="Also reconstruct the files of the resources (e.g: apply IngestTranscoding, StorageCompression). 'false' by default. (New in Orthanc 1.11.0)",
    )


class InstancesIdStatisticsGetResponse(BaseModel):
    DicomDiskSize: Optional[str] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the instance, expressed in bytes',
    )
    DicomDiskSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the instance, expressed in megabytes (MB)',
    )
    DicomUncompressedSize: Optional[str] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the instance, expressed in bytes',
    )
    DicomUncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the instance, expressed in megabytes (MB)',
    )
    DiskSize: Optional[str] = Field(
        None,
        description='Size of the instance on the disk in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    DiskSizeMB: Optional[float] = Field(
        None,
        description='Size of the instance on the disk, expressed in megabytes (MB)',
    )
    UncompressedSize: Optional[str] = Field(
        None,
        description='Size of the instance after decompression in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    UncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size of the instance after decompression, expressed in megabytes (MB). This is different from `DiskSizeMB` iff `StorageCompression` is `true`.',
    )


class ModalitiesIdPutRequest(BaseModel):
    AET: Optional[str] = Field(None, description='AET of the remote DICOM modality')
    AllowEcho: Optional[bool] = Field(
        None,
        description='Whether to accept C-ECHO SCU commands issued by the remote modality',
    )
    AllowFind: Optional[bool] = Field(
        None,
        description='Whether to accept C-FIND SCU commands issued by the remote modality',
    )
    AllowFindWorklist: Optional[bool] = Field(
        None,
        description='Whether to accept C-FIND SCU commands for worklists issued by the remote modality',
    )
    AllowGet: Optional[bool] = Field(
        None,
        description='Whether to accept C-GET SCU commands issued by the remote modality',
    )
    AllowMove: Optional[bool] = Field(
        None,
        description='Whether to accept C-MOVE SCU commands issued by the remote modality',
    )
    AllowStorageCommitment: Optional[bool] = Field(
        None,
        description='Whether to accept storage commitment requests issued by the remote modality',
    )
    AllowStore: Optional[bool] = Field(
        None,
        description='Whether to accept C-STORE SCU commands issued by the remote modality',
    )
    AllowTranscoding: Optional[bool] = Field(
        None,
        description='Whether to allow transcoding for operations initiated by this modality. This option applies to Orthanc C-GET SCP and to Orthanc C-STORE SCU. It only has an effect if the global option `EnableTranscoding` is set to `true`.',
    )
    Host: Optional[str] = Field(
        None,
        description='Host address of the remote DICOM modality (typically, an IP address)',
    )
    Manufacturer: Optional[str] = Field(
        None,
        description='Manufacturer of the remote DICOM modality (check configuration option `DicomModalities` for possible values',
    )
    Port: Optional[float] = Field(
        None, description='TCP port of the remote DICOM modality'
    )
    UseDicomTls: Optional[bool] = Field(
        None,
        description='Whether to use DICOM TLS in the SCU connection initiated by Orthanc (new in Orthanc 1.9.0)',
    )


class ModalitiesIdEchoPostRequest(BaseModel):
    CheckFind: Optional[bool] = Field(
        None,
        description='Issue a dummy C-FIND command after the C-GET SCU, in order to check whether the remote modality knows about Orthanc. This field defaults to the value of the `DicomEchoChecksFind` configuration option. New in Orthanc 1.8.1.',
    )
    Timeout: Optional[float] = Field(
        None, description='Timeout for the C-ECHO command, in seconds'
    )


class ModalitiesIdFindWorklistPostRequest(BaseModel):
    Full: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)',
    )
    Query: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the filter on the values of the DICOM tags',
    )
    Short: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in hexadecimal format',
    )


class ModalitiesIdMovePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Level: Optional[str] = Field(
        None,
        description='Level of the query (`Patient`, `Study`, `Series` or `Instance`)',
    )
    LocalAet: Optional[str] = Field(
        None,
        description='Local AET that is used for this commands, defaults to `DicomAet` configuration option. Ignored if `DicomModalities` already sets `LocalAet` for this modality.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='List of queries identifying all the DICOM resources to be sent',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    TargetAet: Optional[str] = Field(
        None,
        description='Target AET that will be used by the remote DICOM modality as a target for its C-STORE SCU commands, defaults to `DicomAet` configuration option in order to do a simple query/retrieve',
    )
    Timeout: Optional[float] = Field(
        None, description='Timeout for the C-MOVE command, in seconds'
    )


class ModalitiesIdMovePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class ModalitiesIdQueryPostRequest(BaseModel):
    Level: Optional[str] = Field(
        None,
        description='Level of the query (`Patient`, `Study`, `Series` or `Instance`)',
    )
    LocalAet: Optional[str] = Field(
        None,
        description='Local AET that is used for this commands, defaults to `DicomAet` configuration option. Ignored if `DicomModalities` already sets `LocalAet` for this modality.',
    )
    Normalize: Optional[bool] = Field(
        None,
        description='Whether to normalize the query, i.e. whether to wipe out from the query, the DICOM tags that are not applicable for the query-retrieve level of interest',
    )
    Query: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the filter on the values of the DICOM tags',
    )
    Timeout: Optional[float] = Field(
        None,
        description='Timeout for the C-FIND command and subsequent C-MOVE retrievals, in seconds (new in Orthanc 1.9.1)',
    )


class ModalitiesIdQueryPostResponse(BaseModel):
    ID: Optional[Dict[str, Any]] = Field(
        None, description='Identifier of the query, to be used with `/queries/{id}`'
    )
    Path: Optional[Dict[str, Any]] = Field(
        None, description='Root path to the query in the REST API'
    )


class ModalitiesIdStorageCommitmentPostRequest(BaseModel):
    DicomInstances: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='List of DICOM resources that are not necessarily stored within Orthanc, but that must be checked by storage commitment. This is a list of JSON objects that must contain the `SOPClassUID` and `SOPInstanceUID` fields.',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of the DICOM resources to be checked by storage commitment',
    )
    Timeout: Optional[float] = Field(
        None,
        description='Timeout for the storage commitment command (new in Orthanc 1.9.1)',
    )


class ModalitiesIdStorageCommitmentPostResponse(BaseModel):
    ID: Optional[Dict[str, Any]] = Field(
        None,
        description='Identifier of the storage commitment report, to be used with `/storage-commitment/{id}`',
    )
    Path: Optional[Dict[str, Any]] = Field(
        None, description='Root path to the storage commitment report in the REST API'
    )


class ModalitiesIdStorePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    CalledAet: Optional[str] = Field(
        None,
        description='Called AET that is used for this commands, defaults to `AET` configuration option. Allows you to overwrite the destination AET for a specific operation.',
    )
    Host: Optional[str] = Field(
        None,
        description='Host that is used for this commands, defaults to `Host` configuration option. Allows you to overwrite the destination host for a specific operation.',
    )
    LocalAet: Optional[str] = Field(
        None,
        description='Local AET that is used for this commands, defaults to `DicomAet` configuration option. Ignored if `DicomModalities` already sets `LocalAet` for this modality.',
    )
    MoveOriginatorAet: Optional[str] = Field(
        None,
        description='Move originator AET that is used for this commands, in order to fake a C-MOVE SCU',
    )
    MoveOriginatorID: Optional[float] = Field(
        None,
        description='Move originator ID that is used for this commands, in order to fake a C-MOVE SCU',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Port: Optional[float] = Field(
        None,
        description='Port that is used for this commands, defaults to `Port` configuration option. Allows you to overwrite the destination port for a specific operation.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of all the DICOM resources to be sent',
    )
    StorageCommitment: Optional[bool] = Field(
        None,
        description='Whether to chain C-STORE with DICOM storage commitment to validate the success of the transmission: https://book.orthanc-server.com/users/storage-commitment.html#chaining-c-store-with-storage-commitment',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Timeout: Optional[float] = Field(
        None, description='Timeout for the C-STORE command, in seconds'
    )


class ModalitiesIdStorePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class ModalitiesIdStoreStraightPostResponse(BaseModel):
    SOPClassUID: Optional[str] = Field(
        None,
        description='SOP class UID of the DICOM instance, if the C-STORE SCU has succeeded',
    )
    SOPInstanceUID: Optional[str] = Field(
        None,
        description='SOP instance UID of the DICOM instance, if the C-STORE SCU has succeeded',
    )


class PatientsIdAnonymizePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    DicomVersion: Optional[str] = Field(
        None,
        description='Version of the DICOM standard to be used for anonymization. Check out configuration option `DeidentifyLogsDicomVersion` for possible values.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='List of DICOM tags whose value must not be destroyed by the anonymization. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    KeepPrivateTags: Optional[bool] = Field(
        None,
        description='Keep the private tags from the DICOM instances (defaults to `false`)',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of additional tags to be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class PatientsIdAnonymizePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class PatientsIdArchivePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class PatientsIdArchivePostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class PatientsIdMediaPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Extended: Optional[bool] = Field(
        None,
        description='If `true`, will include additional tags such as `SeriesDescription`, leading to a so-called *extended DICOMDIR*. Default value is `false`.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class PatientsIdMediaPostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class PatientsIdModifyPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    RemovePrivateTags: Optional[bool] = Field(
        None,
        description='Remove the private tags from the DICOM instances (defaults to `false`)',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class PatientsIdModifyPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class PatientsIdReconstructPostRequest(BaseModel):
    ReconstructFiles: Optional[bool] = Field(
        None,
        description="Also reconstruct the files of the resources (e.g: apply IngestTranscoding, StorageCompression). 'false' by default. (New in Orthanc 1.11.0)",
    )


class PatientsIdStatisticsGetResponse(BaseModel):
    CountInstances: Optional[float] = Field(
        None, description='Number of child instances within this patient'
    )
    CountSeries: Optional[float] = Field(
        None, description='Number of child series within this patient'
    )
    CountStudies: Optional[float] = Field(
        None, description='Number of child studies within this patient'
    )
    DicomDiskSize: Optional[str] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the patient, expressed in bytes',
    )
    DicomDiskSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the patient, expressed in megabytes (MB)',
    )
    DicomUncompressedSize: Optional[str] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the patient, expressed in bytes',
    )
    DicomUncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the patient, expressed in megabytes (MB)',
    )
    DiskSize: Optional[str] = Field(
        None,
        description='Size of the patient on the disk in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    DiskSizeMB: Optional[float] = Field(
        None, description='Size of the patient on the disk, expressed in megabytes (MB)'
    )
    UncompressedSize: Optional[str] = Field(
        None,
        description='Size of the patient after decompression in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    UncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size of the patient after decompression, expressed in megabytes (MB). This is different from `DiskSizeMB` iff `StorageCompression` is `true`.',
    )


class PeersIdPutRequest(BaseModel):
    CertificateFile: Optional[str] = Field(
        None, description='SSL certificate for the HTTPS connections'
    )
    CertificateKeyFile: Optional[str] = Field(
        None, description='Key file for the SSL certificate for the HTTPS connections'
    )
    CertificateKeyPassword: Optional[str] = Field(
        None,
        description='Key password for the SSL certificate for the HTTPS connections',
    )
    HttpHeaders: Optional[Dict[str, Any]] = Field(
        None,
        description='HTTP headers to be used for the connections to the remote peer',
    )
    Password: Optional[str] = Field(None, description='Password for the credentials')
    URL: Optional[str] = Field(
        None,
        description='URL of the root of the REST API of the remote Orthanc peer, for instance `http://localhost:8042/`',
    )
    Username: Optional[str] = Field(None, description='Username for the credentials')


class PeersIdStorePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Compress: Optional[bool] = Field(
        None,
        description='Whether to compress the DICOM instances using gzip before the actual sending',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of all the DICOM resources to be sent',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode to the provided DICOM transfer syntax before the actual sending',
    )


class PeersIdStorePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class PeersIdStoreStraightPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None,
        description='Orthanc identifier of the DICOM instance in the remote Orthanc peer',
    )
    ParentPatient: Optional[str] = Field(
        None,
        description='Orthanc identifier of the parent patient in the remote Orthanc peer',
    )
    ParentSeries: Optional[str] = Field(
        None,
        description='Orthanc identifier of the parent series in the remote Orthanc peer',
    )
    ParentStudy: Optional[str] = Field(
        None,
        description='Orthanc identifier of the parent study in the remote Orthanc peer',
    )
    Path: Optional[str] = Field(
        None, description='Path to the DICOM instance in the remote Orthanc server'
    )
    Status: Optional[str] = Field(None, description='Status of the store operation')


class QueriesIdAnswersIndexQueryInstancesPostRequest(BaseModel):
    Query: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the filter on the values of the DICOM tags',
    )
    Timeout: Optional[float] = Field(
        None,
        description='Timeout for the C-FIND command, in seconds (new in Orthanc 1.9.1)',
    )


class QueriesIdAnswersIndexQueryInstancesPostResponse(BaseModel):
    ID: Optional[Dict[str, Any]] = Field(
        None, description='Identifier of the query, to be used with `/queries/{id}`'
    )
    Path: Optional[Dict[str, Any]] = Field(
        None, description='Root path to the query in the REST API'
    )


class QueriesIdAnswersIndexQuerySeriesPostRequest(BaseModel):
    Query: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the filter on the values of the DICOM tags',
    )
    Timeout: Optional[float] = Field(
        None,
        description='Timeout for the C-FIND command, in seconds (new in Orthanc 1.9.1)',
    )


class QueriesIdAnswersIndexQuerySeriesPostResponse(BaseModel):
    ID: Optional[Dict[str, Any]] = Field(
        None, description='Identifier of the query, to be used with `/queries/{id}`'
    )
    Path: Optional[Dict[str, Any]] = Field(
        None, description='Root path to the query in the REST API'
    )


class QueriesIdAnswersIndexQueryStudiesPostRequest(BaseModel):
    Query: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the filter on the values of the DICOM tags',
    )
    Timeout: Optional[float] = Field(
        None,
        description='Timeout for the C-FIND command, in seconds (new in Orthanc 1.9.1)',
    )


class QueriesIdAnswersIndexQueryStudiesPostResponse(BaseModel):
    ID: Optional[Dict[str, Any]] = Field(
        None, description='Identifier of the query, to be used with `/queries/{id}`'
    )
    Path: Optional[Dict[str, Any]] = Field(
        None, description='Root path to the query in the REST API'
    )


class QueriesIdAnswersIndexRetrievePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Full: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Simplify: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in human-readable format (using the symbolic name of the tags)',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    TargetAet: Optional[str] = Field(
        None,
        description='AET of the target modality. By default, the AET of Orthanc is used, as defined in the `DicomAet` configuration option.',
    )
    Timeout: Optional[float] = Field(
        None, description='Timeout for the C-MOVE command, in seconds'
    )


class QueriesIdAnswersIndexRetrievePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class QueriesIdRetrievePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Full: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Simplify: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in human-readable format (using the symbolic name of the tags)',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    TargetAet: Optional[str] = Field(
        None,
        description='AET of the target modality. By default, the AET of Orthanc is used, as defined in the `DicomAet` configuration option.',
    )
    Timeout: Optional[float] = Field(
        None, description='Timeout for the C-MOVE command, in seconds'
    )


class QueriesIdRetrievePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class SeriesIdAnonymizePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    DicomVersion: Optional[str] = Field(
        None,
        description='Version of the DICOM standard to be used for anonymization. Check out configuration option `DeidentifyLogsDicomVersion` for possible values.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='List of DICOM tags whose value must not be destroyed by the anonymization. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    KeepPrivateTags: Optional[bool] = Field(
        None,
        description='Keep the private tags from the DICOM instances (defaults to `false`)',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of additional tags to be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class SeriesIdAnonymizePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class SeriesIdArchivePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class SeriesIdArchivePostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class SeriesIdMediaPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Extended: Optional[bool] = Field(
        None,
        description='If `true`, will include additional tags such as `SeriesDescription`, leading to a so-called *extended DICOMDIR*. Default value is `false`.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class SeriesIdMediaPostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class SeriesIdModifyPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    RemovePrivateTags: Optional[bool] = Field(
        None,
        description='Remove the private tags from the DICOM instances (defaults to `false`)',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class SeriesIdModifyPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class SeriesIdOrderedSlicesGetResponse(BaseModel):
    Dicom: Optional[List[str]] = Field(
        None, description='Ordered list of paths to DICOM instances'
    )
    Slices: Optional[List[str]] = Field(
        None,
        description='Ordered list of paths to frames. It is recommended to use this field, as it is also valid in the case of multiframe images.',
    )
    SlicesShort: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='Same information as the `Slices` field, but in a compact form',
    )
    Type: Optional[str] = Field(
        None,
        description='Can be `Volume` (for 3D volumes) or `Sequence` (notably for cine images)',
    )


class SeriesIdReconstructPostRequest(BaseModel):
    ReconstructFiles: Optional[bool] = Field(
        None,
        description="Also reconstruct the files of the resources (e.g: apply IngestTranscoding, StorageCompression). 'false' by default. (New in Orthanc 1.11.0)",
    )


class SeriesIdStatisticsGetResponse(BaseModel):
    CountInstances: Optional[float] = Field(
        None, description='Number of child instances within this series'
    )
    DicomDiskSize: Optional[str] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the series, expressed in bytes',
    )
    DicomDiskSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the series, expressed in megabytes (MB)',
    )
    DicomUncompressedSize: Optional[str] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the series, expressed in bytes',
    )
    DicomUncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the series, expressed in megabytes (MB)',
    )
    DiskSize: Optional[str] = Field(
        None,
        description='Size of the series on the disk in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    DiskSizeMB: Optional[float] = Field(
        None, description='Size of the series on the disk, expressed in megabytes (MB)'
    )
    UncompressedSize: Optional[str] = Field(
        None,
        description='Size of the series after decompression in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    UncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size of the series after decompression, expressed in megabytes (MB). This is different from `DiskSizeMB` iff `StorageCompression` is `true`.',
    )


class StatisticsGetResponse(BaseModel):
    CountInstances: Optional[float] = Field(
        None, description='Number of DICOM instances stored in Orthanc'
    )
    CountPatients: Optional[float] = Field(
        None, description='Number of patients stored in Orthanc'
    )
    CountSeries: Optional[float] = Field(
        None, description='Number of DICOM series stored in Orthanc'
    )
    CountStudies: Optional[float] = Field(
        None, description='Number of DICOM studies stored in Orthanc'
    )
    TotalDiskSize: Optional[str] = Field(
        None, description='Size of the storage area (in bytes)'
    )
    TotalDiskSizeMB: Optional[float] = Field(
        None, description='Size of the storage area (in megabytes)'
    )
    TotalUncompressedSize: Optional[str] = Field(
        None,
        description='Total size of all the files once uncompressed (in bytes). This corresponds to `TotalDiskSize` if no compression is enabled, cf. `StorageCompression` configuration option',
    )
    TotalUncompressedSizeMB: Optional[float] = Field(
        None, description='Total size of all the files once uncompressed (in megabytes)'
    )


class StorageCommitmentIdGetResponse(BaseModel):
    Failures: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='List of failures that have been encountered during the storage commitment request',
    )
    RemoteAET: Optional[str] = Field(
        None, description='AET of the remote DICOM modality'
    )
    Status: Optional[str] = Field(
        None,
        description='Can be `Success`, `Failure`, or `Pending` (the latter means that no report has been received yet)',
    )
    Success: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='List of DICOM instances that have been acknowledged by the remote modality, each one is reported as a JSON object containing the `SOPClassUID` and `SOPInstanceUID` DICOM tags',
    )


class StudiesIdAnonymizePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    DicomVersion: Optional[str] = Field(
        None,
        description='Version of the DICOM standard to be used for anonymization. Check out configuration option `DeidentifyLogsDicomVersion` for possible values.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='List of DICOM tags whose value must not be destroyed by the anonymization. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    KeepPrivateTags: Optional[bool] = Field(
        None,
        description='Keep the private tags from the DICOM instances (defaults to `false`)',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of additional tags to be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class StudiesIdAnonymizePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class StudiesIdArchivePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class StudiesIdArchivePostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class StudiesIdMediaPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Extended: Optional[bool] = Field(
        None,
        description='If `true`, will include additional tags such as `SeriesDescription`, leading to a so-called *extended DICOMDIR*. Default value is `false`.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class StudiesIdMediaPostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class StudiesIdMergePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `true`, instructs Orthanc to keep a copy of the original resources in their source study. By default, the original resources are deleted from Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='The list of DICOM resources (studies, series, and/or instances) to be merged into the study of interest (mandatory option)',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )


class StudiesIdMergePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class StudiesIdModifyPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    RemovePrivateTags: Optional[bool] = Field(
        None,
        description='Remove the private tags from the DICOM instances (defaults to `false`)',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class StudiesIdModifyPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class StudiesIdReconstructPostRequest(BaseModel):
    ReconstructFiles: Optional[bool] = Field(
        None,
        description="Also reconstruct the files of the resources (e.g: apply IngestTranscoding, StorageCompression). 'false' by default. (New in Orthanc 1.11.0)",
    )


class StudiesIdSplitPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Instances: Optional[List[str]] = Field(
        None,
        description='The list of instances to be separated from the parent study. These instances must all be children of the same source study, that is specified in the URI.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `true`, instructs Orthanc to keep a copy of the original series/instances in the source study. By default, the original series/instances are deleted from Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of tags that must be removed in the new study (from the same modules as in the `Replace` option)',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the new study. These tags must be part of the "Patient Module Attributes" or the "General Study Module Attributes", as specified by the DICOM 2011 standard in Tables C.7-1 and C.7-3.',
    )
    Series: Optional[List[str]] = Field(
        None,
        description='The list of series to be separated from the parent study. These series must all be children of the same source study, that is specified in the URI.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )


class StudiesIdSplitPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class StudiesIdStatisticsGetResponse(BaseModel):
    CountInstances: Optional[float] = Field(
        None, description='Number of child instances within this study'
    )
    CountSeries: Optional[float] = Field(
        None, description='Number of child series within this study'
    )
    DicomDiskSize: Optional[str] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the study, expressed in bytes',
    )
    DicomDiskSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the DICOM instances associated with the study, expressed in megabytes (MB)',
    )
    DicomUncompressedSize: Optional[str] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the study, expressed in bytes',
    )
    DicomUncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size on the disk of the uncompressed DICOM instances associated with the study, expressed in megabytes (MB)',
    )
    DiskSize: Optional[str] = Field(
        None,
        description='Size of the study on the disk in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    DiskSizeMB: Optional[float] = Field(
        None, description='Size of the study on the disk, expressed in megabytes (MB)'
    )
    UncompressedSize: Optional[str] = Field(
        None,
        description='Size of the study after decompression in bytes, expressed as a string for 64bit compatibility with JSON',
    )
    UncompressedSizeMB: Optional[float] = Field(
        None,
        description='Size of the study after decompression, expressed in megabytes (MB). This is different from `DiskSizeMB` iff `StorageCompression` is `true`.',
    )


class SystemGetResponse(BaseModel):
    ApiVersion: Optional[float] = Field(None, description='Version of the REST API')
    CheckRevisions: Optional[bool] = Field(
        None,
        description='Whether Orthanc handle revisions of metadata and attachments to deal with multiple writers (new in Orthanc 1.9.2)',
    )
    DatabaseBackendPlugin: Optional[str] = Field(
        None,
        description='Information about the installed database index plugin (`null` if no such plugin is installed)',
    )
    DatabaseServerIdentifier: Optional[str] = Field(
        None,
        description='ID of the server in the database (when running multiple Orthanc on the same DB)',
    )
    DatabaseVersion: Optional[float] = Field(
        None,
        description='Version of the database: https://book.orthanc-server.com/developers/db-versioning.html',
    )
    DicomAet: Optional[str] = Field(None, description='The DICOM AET of Orthanc')
    DicomPort: Optional[float] = Field(
        None, description='The port to the DICOM server of Orthanc'
    )
    HttpPort: Optional[float] = Field(
        None, description='The port to the HTTP server of Orthanc'
    )
    IngestTranscoding: Optional[str] = Field(
        None,
        description='Whether instances are transcoded when ingested into Orthanc (`` if no transcoding is performed) (new in Orthanc 1.11.0)',
    )
    IsHttpServerSecure: Optional[bool] = Field(
        None,
        description='Whether the REST API is properly secured (assuming no reverse proxy is in use): https://book.orthanc-server.com/faq/security.html#securing-the-http-server',
    )
    MainDicomTags: Optional[Dict[str, Any]] = Field(
        None,
        description='The list of MainDicomTags saved in DB for each resource level (new in Orthanc 1.11.0)',
    )
    MaximumStorageMode: Optional[str] = Field(
        None, description='The configured MaximumStorageMode (new in Orthanc 1.11.3)'
    )
    MaximumStorageSize: Optional[float] = Field(
        None,
        description='The configured MaximumStorageSize in MB (new in Orthanc 1.11.3)',
    )
    Name: Optional[str] = Field(
        None,
        description='The name of the Orthanc server, cf. the `Name` configuration option',
    )
    OverwriteInstances: Optional[bool] = Field(
        None,
        description='Whether instances are overwritten when re-ingested (new in Orthanc 1.11.0)',
    )
    PluginsEnabled: Optional[bool] = Field(
        None, description='Whether Orthanc was built with support for plugins'
    )
    StorageAreaPlugin: Optional[str] = Field(
        None,
        description='Information about the installed storage area plugin (`null` if no such plugin is installed)',
    )
    StorageCompression: Optional[bool] = Field(
        None,
        description='Whether storage compression is enabled (new in Orthanc 1.11.0)',
    )
    Version: Optional[str] = Field(None, description='Version of Orthanc')


class ToolsBulkAnonymizePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    DicomVersion: Optional[str] = Field(
        None,
        description='Version of the DICOM standard to be used for anonymization. Check out configuration option `DeidentifyLogsDicomVersion` for possible values.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='List of DICOM tags whose value must not be destroyed by the anonymization. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    KeepPrivateTags: Optional[bool] = Field(
        None,
        description='Keep the private tags from the DICOM instances (defaults to `false`)',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of additional tags to be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of the patients/studies/series/instances of interest.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class ToolsBulkAnonymizePostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class ToolsBulkContentPostRequest(BaseModel):
    Full: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)',
    )
    Level: Optional[str] = Field(
        None,
        description='This optional argument specifies the level of interest (can be `Patient`, `Study`, `Series` or `Instance`). Orthanc will loop over the items inside `Resources`, and explore upward or downward in the DICOM hierarchy in order to find the level of interest.',
    )
    Metadata: Optional[bool] = Field(
        None,
        description='If set to `true` (default value), the metadata associated with the resources will also be retrieved.',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of the patients/studies/series/instances of interest.',
    )
    Short: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in hexadecimal format',
    )


class ToolsBulkDeletePostRequest(BaseModel):
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of the patients/studies/series/instances of interest.',
    )


class ToolsBulkModifyPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in asynchronous mode, which means that the REST API call will immediately return, reporting the identifier of a job. Prefer this flavor wherever possible.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world',
    )
    Keep: Optional[List[str]] = Field(
        None,
        description='Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.',
    )
    KeepSource: Optional[bool] = Field(
        None,
        description='If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.',
    )
    Level: Optional[str] = Field(
        None,
        description='Level of the modification (`Patient`, `Study`, `Series` or `Instance`). If absent, the level defaults to `Instance`, but is set to `Patient` if `PatientID` is modified, to `Study` if `StudyInstanceUID` is modified, or to `Series` if `SeriesInstancesUID` is modified. (new in Orthanc 1.9.7)',
    )
    Permissive: Optional[bool] = Field(
        None,
        description='If `true`, ignore errors during the individual steps of the job.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Replace`'
    )
    Remove: Optional[List[str]] = Field(
        None,
        description='List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    RemovePrivateTags: Optional[bool] = Field(
        None,
        description='Remove the private tags from the DICOM instances (defaults to `false`)',
    )
    Replace: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).',
    )
    Resources: Optional[List[str]] = Field(
        None,
        description='List of the Orthanc identifiers of the patients/studies/series/instances of interest.',
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, run the job in synchronous mode, which means that the HTTP answer will directly contain the result of the job. This is the default, easy behavior, but it is *not* desirable for long jobs, as it might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='Transcode the DICOM instances to the provided DICOM transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class ToolsBulkModifyPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='In asynchronous mode, identifier of the job'
    )
    Path: Optional[str] = Field(
        None, description='In asynchronous mode, path to access the job in the REST API'
    )


class ToolsCreateArchivePostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[str]] = Field(
        None, description='The list of Orthanc identifiers of interest.'
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class ToolsCreateArchivePostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class ToolsCreateDicomPostRequest(BaseModel):
    Content: Optional[str] = Field(
        None,
        description='This field can be used to embed an image (pixel data) or a PDF inside the created DICOM instance. The PNG image, the JPEG image or the PDF file must be provided using their [data URI scheme encoding](https://en.wikipedia.org/wiki/Data_URI_scheme). This field can possibly contain a JSON array, in which case a DICOM series is created containing one DICOM instance for each item in the `Content` field.',
    )
    Force: Optional[bool] = Field(
        None,
        description='Avoid the consistency checks for the DICOM tags that enforce the DICOM model of the real-world. You can notably use this flag if you need to manually set the tags `StudyInstanceUID`, `SeriesInstanceUID`, or `SOPInstanceUID`. Be careful with this feature.',
    )
    InterpretBinaryTags: Optional[bool] = Field(
        None,
        description='If some value in the `Tags` associative array is formatted according to some [data URI scheme encoding](https://en.wikipedia.org/wiki/Data_URI_scheme), whether this value is decoded to a binary value or kept as such (`true` by default)',
    )
    Parent: Optional[str] = Field(
        None,
        description='If present, the newly created instance will be attached to the parent DICOM resource whose Orthanc identifier is contained in this field. The DICOM tags of the parent modules in the DICOM hierarchy will be automatically copied to the newly created instance.',
    )
    PrivateCreator: Optional[str] = Field(
        None, description='The private creator to be used for private tags in `Tags`'
    )
    Tags: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the tags of the new instance to be created',
    )


class ToolsCreateDicomPostResponse(BaseModel):
    ID: Optional[str] = Field(
        None, description='Orthanc identifier of the newly created instance'
    )
    Path: Optional[str] = Field(
        None, description='Path to access the instance in the REST API'
    )


class ToolsCreateMediaPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Extended: Optional[bool] = Field(
        None,
        description='If `true`, will include additional tags such as `SeriesDescription`, leading to a so-called *extended DICOMDIR*. Default value is `false`.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[str]] = Field(
        None, description='The list of Orthanc identifiers of interest.'
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class ToolsCreateMediaPostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class ToolsCreateMediaExtendedPostRequest(BaseModel):
    Asynchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in asynchronous mode, which means that a job is submitted to create the archive in background.',
    )
    Extended: Optional[bool] = Field(
        None,
        description='If `true`, will include additional tags such as `SeriesDescription`, leading to a so-called *extended DICOMDIR*. Default value is `true`.',
    )
    Priority: Optional[float] = Field(
        None,
        description='In asynchronous mode, the priority of the job. The lower the value, the higher the priority.',
    )
    Resources: Optional[List[str]] = Field(
        None, description='The list of Orthanc identifiers of interest.'
    )
    Synchronous: Optional[bool] = Field(
        None,
        description='If `true`, create the archive in synchronous mode, which means that the HTTP answer will directly contain the ZIP file. This is the default, easy behavior. However, if global configuration option "SynchronousZipStream" is set to "false", asynchronous transfers should be preferred for large amount of data, as the creation of the temporary file might lead to network timeouts.',
    )
    Transcode: Optional[str] = Field(
        None,
        description='If present, the DICOM files in the archive will be transcoded to the provided transfer syntax: https://book.orthanc-server.com/faq/transcoding.html',
    )


class ToolsCreateMediaExtendedPostResponse(BaseModel):
    ID: Optional[str] = Field(None, description='Identifier of the job')
    Path: Optional[str] = Field(
        None, description='Path to access the job in the REST API'
    )


class ToolsDicomEchoPostRequest(BaseModel):
    AET: Optional[str] = Field(None, description='AET of the remote DICOM modality')
    CheckFind: Optional[bool] = Field(
        None,
        description='Issue a dummy C-FIND command after the C-GET SCU, in order to check whether the remote modality knows about Orthanc. This field defaults to the value of the `DicomEchoChecksFind` configuration option. New in Orthanc 1.8.1.',
    )
    Host: Optional[str] = Field(
        None,
        description='Host address of the remote DICOM modality (typically, an IP address)',
    )
    Manufacturer: Optional[str] = Field(
        None,
        description='Manufacturer of the remote DICOM modality (check configuration option `DicomModalities` for possible values',
    )
    Port: Optional[float] = Field(
        None, description='TCP port of the remote DICOM modality'
    )
    Timeout: Optional[float] = Field(
        None, description='Timeout for the C-ECHO command, in seconds'
    )
    UseDicomTls: Optional[bool] = Field(
        None,
        description='Whether to use DICOM TLS in the SCU connection initiated by Orthanc (new in Orthanc 1.9.0)',
    )


class ToolsFindPostRequest(BaseModel):
    CaseSensitive: Optional[bool] = Field(
        None,
        description='Enable case-sensitive search for PN value representations (defaults to configuration option `CaseSensitivePN`)',
    )
    Expand: Optional[bool] = Field(
        None,
        description='Also retrieve the content of the matching resources, not only their Orthanc identifiers',
    )
    Full: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in full format (tags indexed by their hexadecimal format, associated with their symbolic name and their value)',
    )
    Level: Optional[str] = Field(
        None,
        description='Level of the query (`Patient`, `Study`, `Series` or `Instance`)',
    )
    Limit: Optional[float] = Field(
        None, description='Limit the number of reported resources'
    )
    Query: Optional[Dict[str, Any]] = Field(
        None,
        description='Associative array containing the filter on the values of the DICOM tags',
    )
    RequestedTags: Optional[List[str]] = Field(
        None,
        description='A list of DICOM tags to include in the response (applicable only if "Expand" is set to true).  The tags requested tags are returned in the \'RequestedTags\' field in the response.  Note that, if you are requesting tags that are not listed in the Main Dicom Tags stored in DB, building the response might be slow since Orthanc will need to access the DICOM files.  If not specified, Orthanc will return all Main Dicom Tags to keep backward compatibility with Orthanc prior to 1.11.0.',
    )
    Short: Optional[bool] = Field(
        None,
        description='If set to `true`, report the DICOM tags in hexadecimal format',
    )
    Since: Optional[float] = Field(
        None,
        description='Show only the resources since the provided index (in conjunction with `Limit`)',
    )


class ToolsReconstructPostRequest(BaseModel):
    ReconstructFiles: Optional[bool] = Field(
        None,
        description="Also reconstruct the files of the resources (e.g: apply IngestTranscoding, StorageCompression). 'false' by default. (New in Orthanc 1.11.0)",
    )
